# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

env:
  MSBUILDDISABLENODEREUSE: 1
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 200
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          6.0.300
          7.0.202
    - name: print
      run: |
        echo "REUSE = $MSBUILDDISABLENODEREUSE"
        echo "MSBuildExtensionsPath = $MSBuildExtensionsPath"
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - uses: actions/upload-artifact@v3
      with:
        name: binlog
        path: build.binlog
      
